# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('rt_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('rt_link', models.TextField()),
                ('runtime', models.IntegerField()),
                ('audience_score', models.IntegerField()),
                ('critics_score', models.IntegerField()),
                ('title', models.TextField()),
                ('year', models.IntegerField()),
                ('synopsis', models.TextField()),
                ('mpaa_rating', models.CharField(max_length=50)),
                ('imdb_id', models.CharField(max_length=100)),
                ('actors', models.TextField()),
                ('audience_rating', models.CharField(max_length=50)),
                ('critics_rating', models.CharField(max_length=50)),
            ],
        ),
    ]
